# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
      - releases/*
      - feature/*
    exclude:
      - releases/old/*
      - feature/-working
  paths:
    include:
      - '*'
    exclude:
      - 'docs/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkDirectory: 
    mavenVersionOption: Default
    mavenDirectory: 
    mavenSetM2Home: false
    mavenAuthenticateFeed: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: latest
    goals: 'package'

pr:
  - master
  - releases/*
