# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
      - releases/*
      - feature/*
    exclude:
      - releases/old*
      - feature/*-working
  paths:
    include:
      - '*'
    exclude:
      - 'docs/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkDirectory: 
    mavenVersionOption: Default
    mavenDirectory: 
    mavenSetM2Home: false
    mavenAuthenticateFeed: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: latest
    goals: 'package'

pr:
  - master
  - releases/*

schedules:
  - cron: "30 21 * * Sun-Thu"
    displayName: M-F 3:00 AM (UTC + 5:30) India daily build
    branches:
      include:
      - features/india/*
  - cron: "0 8 * * Mon-Fri"
    displayName: M-F 3:00 AM (UTC - 5) NC daily build
    branches:
      include:
      - features/nc/*
  - cron: "0 3 * * Mon-Fri"
    displayName: M-F 3:00 AM (UTC) daily build
    branches:
      include:
      - master
      - releases/*
  - cron: "0 3 * * Sun"
    displayName: Sunday 3:00 AM (UTC) weekly latest version build
    branches:
      include:
      - releases/lastversion
    always: true
